:imagesdir: Images
:figure-caption: Рисунок

== Лабораторная работа №7 - Happy New Year -

Новогодняя гирлянда: с периодом 50 мс светодиоды поочередно загораются. После того, как все четыре светодиода зажглись, они поочередно гаснут в обратном порядке. Период переключения гирлянды регулируется кнопкой. При каждом нажатии на кнопку период увеличивается на 50 мс. Если период становится равным 1000 мс, последующие нажатия кнопки уменьшают период на 50 мс. Если период сокращается до 50 мс, нажатия кнопки снова приводят к увеличению периода на 50 мс, и так далее.

Обертка, использованая в проекте, иллюстрируется следующей диаграммой классов (рисунок 1):

.Диаграмма классов проекта
image::file1.svg[]

==== Отрывок из файла *main.c*

[source, cpp]
----
extern "C"
{
int __low_level_init(void)
{
   NVIC::ISER0::Write(1 << 28);
   return 1;
}
}

int main()
{

 garlands.Enable();
 garlands.Start();

  for(;;)
  {
    if(garlands.ButtonPressed())
    {
      garlands.PeriodUpdate();
    }
  }
}
----

Для обеспечения требуемого периода переключения используется таймер *TIM2*.

==== Обработчик прерывания по переполнению таймера *TIM2*

[source, cpp]
----
static void Timer2Handler()
    {
      if (TIM2::SR::UIF::UpdatePending::IsSet() && TIM2::DIER::UIE::Enable::IsSet())
      {
       TIM2::SR::UIF::NoUpdate::Set();
       garlands.Switch();
      }
    }
----
